Impl toMap
yudai1204/nasa-hackathon-2023-yokohama pull request #62
Opened 2023-10-09 16:07 UTC by Kyo-s-s

## 概要

Three状態で月に近づくと、Map状態に代わるように

### やったこと

- `orbitControls`のdistanceがminDistanceに一致したときにMapに遷移するようにした

### やらなかったこと(あれば)

- minDistanceのいい感じの調整(適当な値になってる、でも問題ないかも)

## スクリーンショット

## 破壊的変更があるか(あれば内容を記載)

- [ ] YES
- [x] NO

## チェック項目

- [ ] lintが通る
- [x] 複雑なコードにはコメントを記載してある

## 関連Issue

## レビュワーへのコメント

```typescript
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const orbitControlsRef = useRef<any>(null);
```
と書いてしまっています、本当にごめんなさい。
```typescript
const orbitControlsRef = useRef<OrbitControls>(null);
```
と書くべきなんですが、
`'OrbitControls' refers to a value, but is being used as a type here. Did you mean 'typeof OrbitControls'?ts(2749)
type OrbitControls = /*unresolved*/ any` とエラーになってしまったので `any` を使っています。

2023-10-09 16:11 UTC, Kyo-s-s commented
https://github.com/yudai1204/nasa-hackathon-2023-yokohama/assets/86707335/104c3ae6-f20c-4fe5-88db-74a43511fe50

2023-10-09 23:10 UTC, yudai1204 requested changes
比較の方だけ確認お願いします🙇

2023-10-09 23:10 UTC, yudai1204 commented on src/components/useThree/mainCanvas.tsx
> +    if (orbitControls.getDistance() === orbitControls.minDistance) {
```suggestion
    if (orbitControls.getDistance() <= orbitControls.minDistance) {
```

じゃないと、早く動かした時や一部のデバイスで変わってくれなさそう

2023-10-09 23:10 UTC, yudai1204 commented on src/components/useThree/mainCanvas.tsx
> +  const orbitControlsRef = useRef<any>(null);
pcがなく手元で動かせないのと、ここを一生懸命頑張るのは本質的じゃないのでとりあえずヨシとしましょう

2023-10-10 00:06 UTC, ecto0310 commented on src/components/useThree/mainCanvas.tsx
> +  const orbitControlsRef = useRef<any>(null);
```
import { OrbitControls as OrbitControlsImpl } from "three-stdlib/controls/OrbitControls";
```
をimportして型を`OrbitControlsImpl`にすると良さそう?
雑に言ってるので間違えてたらすみません

2023-10-10 02:15 UTC, Kyo-s-s commented on src/components/useThree/mainCanvas.tsx
> +  const orbitControlsRef = useRef<any>(null);
これも書いてみたんですがダメでした(dreiのorbitcontrolsとそうじゃないorbitcontrolsで色々違っていそう？)

2023-10-10 05:42 UTC, Kyo-s-s commented on src/components/useThree/mainCanvas.tsx
> +  const orbitControlsRef = useRef<any>(null);
ごめんなさい！！！！

2023-10-10 05:43 UTC, ecto0310 commented on src/components/useThree/mainCanvas.tsx
> +  const orbitControlsRef = useRef<any>(null);
https://github.com/yudai1204/nasa-hackathon-2023-yokohama/commit/4f74373f35229ade297a2d4de3da79499817bb1c
一応build通って型チェック通るのでうーん...

2023-10-10 06:18 UTC, yudai1204 commented on src/components/useThree/mainCanvas.tsx
> +  const orbitControlsRef = useRef<any>(null);
importじゃなくてimport typeにしたら通りそうかも？
何もテストしていないので嘘ついてたらごめん

2023-10-10 06:52 UTC, Kyo-s-s commented on src/components/useThree/mainCanvas.tsx
> +  const orbitControlsRef = useRef<any>(null);
https://github.com/yudai1204/nasa-hackathon-2023-yokohama/commit/4f74373f35229ade297a2d4de3da79499817bb1c これでよさそう！ 手元でやったとき、`import { OrbitControls } from "@react-three/drei";` を消して `import { OrbitControls as OrbitControlsImpl } from "three-stdlib";` を書いていたので動いていなかったっぽいです、ごめんなさい

2023-10-10 07:03 UTC, ecto0310 approved these changes

2023-10-10 07:11 UTC, yudai1204 commented on src/components/useThree/mainCanvas.tsx
> +  const orbitControlsRef = useRef<any>(null);
型だけをimportするときはimport typeにすることを心がけて欲しいです！
(これはlintの設定を忘れていた僕が悪いですごめんなさい)

2023-10-10 08:15 UTC, yudai1204 approved these changes
![LGTM](https://github.com/yudai1204/nasa-hackathon-2023-yokohama/assets/59430508/bf7bf0a2-7b35-4649-9379-7f64ed288096)

2023-10-10 08:16 UTC, Kyo-s-s commented
```typescript
import type { OrbitControls as OrbitControlsImpl } from "three-stdlib";
```

と `type` を追加しましtあ

2023-10-10 08:18 UTC, merged